-- V17: mở rộng danh mục ICD-10 từ 86 mã lên ~670 mã.
--
-- PHẠM VI: các mã một phòng khám đa khoa ngoại trú thực sự dùng, trải đủ 22 chương của
-- ICD-10. ĐÂY KHÔNG PHẢI bản ICD-10 đầy đủ của WHO (~14.000 mã kể cả mã 4 ký tự).
--
-- Vì sao dừng ở mức này chứ không nạp trọn bộ:
--   1. Endpoint GET /api/doctor/icd10/all trả NGUYÊN cả bảng về trình duyệt để lọc tại chỗ
--      (xem Icd10Controller — đó là tối ưu có chủ đích, thay cho 3 query mỗi ký tự gõ).
--      670 dòng ≈ 37KB thô / ~8KB sau gzip: vẫn nằm gọn trong thiết kế đó.
--      14.000 dòng ≈ 1,3MB và sẽ bị MAX_ALL = 5000 cắt ÂM THẦM ở mã thứ 5000.
--   2. Danh mục y tế phải chính xác. Bộ này gồm các mã có tên tiếng Việt đối chiếu được;
--      muốn trọn bộ theo Thông tư Bộ Y tế thì nạp từ file gốc, đừng gõ tay.
--
-- Bổ sung thêm về sau: insert into icd10_codes values ('MA','Tên') on conflict do nothing;
-- Mã ở cấp 3 ký tự (nhóm bệnh) trừ vài mã 4 ký tự quá thông dụng để bỏ (vd M54.3).

insert into icd10_codes (code, name) values

-- ===== Chương I: Bệnh nhiễm trùng và ký sinh trùng (A00-B99) =====
('A00', 'Bệnh tả'),
('A01', 'Thương hàn và phó thương hàn'),
('A02', 'Nhiễm Salmonella khác'),
('A03', 'Lỵ trực khuẩn (Shigella)'),
('A04', 'Nhiễm khuẩn đường ruột do vi khuẩn khác'),
('A05', 'Ngộ độc thức ăn do vi khuẩn khác'),
('A06', 'Lỵ amíp'),
('A07', 'Bệnh đường ruột do đơn bào khác'),
('A15', 'Lao hô hấp có xác nhận vi khuẩn học và mô học'),
('A16', 'Lao hô hấp không xác nhận vi khuẩn học hoặc mô học'),
('A17', 'Lao hệ thần kinh'),
('A18', 'Lao các cơ quan khác'),
('A19', 'Lao kê'),
('A30', 'Bệnh phong (Hansen)'),
('A36', 'Bạch hầu'),
('A37', 'Ho gà'),
('A38', 'Tinh hồng nhiệt'),
('A39', 'Nhiễm não mô cầu'),
('A40', 'Nhiễm khuẩn huyết do liên cầu'),
('A41', 'Nhiễm khuẩn huyết khác'),
('A46', 'Viêm quầng'),
('A48', 'Bệnh do vi khuẩn khác, không phân loại nơi khác'),
('A49', 'Nhiễm khuẩn không xác định vị trí'),
('A50', 'Giang mai bẩm sinh'),
('A51', 'Giang mai sớm'),
('A52', 'Giang mai muộn'),
('A53', 'Giang mai khác và không xác định'),
('A54', 'Nhiễm lậu cầu'),
('A56', 'Bệnh lây qua đường tình dục do Chlamydia khác'),
('A59', 'Nhiễm Trichomonas'),
('A60', 'Nhiễm Herpes sinh dục và hậu môn'),
('A63', 'Bệnh lây qua đường tình dục khác'),
('A64', 'Bệnh lây qua đường tình dục không xác định'),
('A69', 'Nhiễm xoắn khuẩn khác'),
('A80', 'Bại liệt cấp'),
('A82', 'Bệnh dại'),
('A83', 'Viêm não do virus truyền qua muỗi'),
('A87', 'Viêm màng não do virus'),
('A88', 'Nhiễm virus khác của hệ thần kinh trung ương'),
('A91', 'Sốt xuất huyết Dengue'),
('A92', 'Sốt do virus khác truyền qua muỗi'),
('A98', 'Sốt xuất huyết do virus khác'),
('B00', 'Nhiễm virus Herpes simplex'),
('B05', 'Sởi'),
('B06', 'Rubella (sởi Đức)'),
('B07', 'Hạt cơm do virus (mụn cóc)'),
('B08', 'Nhiễm virus khác có tổn thương da và niêm mạc'),
('B09', 'Nhiễm virus không xác định có tổn thương da'),
('B15', 'Viêm gan A cấp'),
('B16', 'Viêm gan B cấp'),
('B17', 'Viêm gan virus cấp khác'),
('B19', 'Viêm gan virus không xác định'),
('B20', 'Bệnh do virus gây suy giảm miễn dịch ở người (HIV)'),
('B26', 'Quai bị'),
('B27', 'Tăng bạch cầu đơn nhân nhiễm khuẩn'),
('B30', 'Viêm kết mạc do virus'),
('B34', 'Nhiễm virus không xác định vị trí'),
('B36', 'Bệnh nấm nông khác'),
('B37', 'Nhiễm nấm Candida'),
('B44', 'Nhiễm nấm Aspergillus'),
('B49', 'Nhiễm nấm không xác định'),
('B50', 'Sốt rét do Plasmodium falciparum'),
('B51', 'Sốt rét do Plasmodium vivax'),
('B54', 'Sốt rét không xác định'),
('B68', 'Nhiễm sán dây'),
('B76', 'Nhiễm giun móc'),
('B77', 'Nhiễm giun đũa'),
('B79', 'Nhiễm giun tóc'),
('B80', 'Nhiễm giun kim'),
('B82', 'Nhiễm ký sinh trùng đường ruột không xác định'),
('B83', 'Nhiễm giun sán khác'),
('B85', 'Chấy rận'),
('B86', 'Ghẻ'),
('B99', 'Bệnh nhiễm khuẩn khác và không xác định'),

-- ===== Chương II: Bướu tân sinh (C00-D48) =====
('C16', 'U ác của dạ dày'),
('C18', 'U ác của đại tràng'),
('C20', 'U ác của trực tràng'),
('C22', 'U ác của gan và đường mật trong gan'),
('C34', 'U ác của phế quản và phổi'),
('C50', 'U ác của vú'),
('C53', 'U ác của cổ tử cung'),
('C61', 'U ác của tuyến tiền liệt'),
('C73', 'U ác của tuyến giáp'),
('D12', 'U lành của đại tràng, trực tràng và hậu môn'),
('D17', 'U mỡ lành'),
('D21', 'U lành khác của mô liên kết và mô mềm'),
('D22', 'Nơ vi hắc tố (nốt ruồi)'),
('D23', 'U lành khác của da'),
('D24', 'U lành của tuyến vú'),
('D25', 'U cơ trơn tử cung (u xơ tử cung)'),
('D27', 'U lành của buồng trứng'),
('D34', 'U lành của tuyến giáp'),
('D36', 'U lành ở vị trí khác'),
('D48', 'U chưa rõ tính chất ở vị trí khác'),

-- ===== Chương III: Bệnh máu và cơ quan tạo máu (D50-D89) =====
('D50', 'Thiếu máu thiếu sắt'),
('D51', 'Thiếu máu do thiếu vitamin B12'),
('D52', 'Thiếu máu do thiếu folate'),
('D53', 'Thiếu máu dinh dưỡng khác'),
('D55', 'Thiếu máu do rối loạn enzym'),
('D56', 'Thalassemia'),
('D58', 'Thiếu máu tan máu di truyền khác'),
('D59', 'Thiếu máu tan máu mắc phải'),
('D61', 'Thiếu máu bất sản khác'),
('D64', 'Thiếu máu khác'),
('D68', 'Rối loạn đông máu khác'),
('D69', 'Ban xuất huyết và tình trạng xuất huyết khác'),
('D70', 'Giảm bạch cầu hạt'),
('D72', 'Rối loạn khác của bạch cầu'),
('D73', 'Bệnh của lách'),
('D75', 'Bệnh khác của máu và cơ quan tạo máu'),
('D89', 'Rối loạn khác liên quan cơ chế miễn dịch'),

-- ===== Chương IV: Nội tiết, dinh dưỡng và chuyển hóa (E00-E90) =====
('E01', 'Rối loạn tuyến giáp liên quan thiếu iod'),
('E02', 'Suy giáp dưới lâm sàng do thiếu iod'),
('E06', 'Viêm tuyến giáp'),
('E07', 'Rối loạn khác của tuyến giáp'),
('E13', 'Đái tháo đường xác định khác'),
('E14', 'Đái tháo đường không xác định'),
('E16', 'Rối loạn khác của bài tiết nội tiết tụy'),
('E20', 'Suy cận giáp'),
('E21', 'Cường cận giáp'),
('E22', 'Cường chức năng tuyến yên'),
('E23', 'Giảm chức năng tuyến yên'),
('E24', 'Hội chứng Cushing'),
('E27', 'Rối loạn khác của tuyến thượng thận'),
('E28', 'Rối loạn chức năng buồng trứng (gồm buồng trứng đa nang)'),
('E29', 'Rối loạn chức năng tinh hoàn'),
('E34', 'Rối loạn nội tiết khác'),
('E43', 'Suy dinh dưỡng nặng thể phối hợp'),
('E44', 'Suy dinh dưỡng protein - năng lượng mức độ vừa và nhẹ'),
('E46', 'Suy dinh dưỡng protein - năng lượng không xác định'),
('E50', 'Thiếu vitamin A'),
('E51', 'Thiếu thiamin (vitamin B1)'),
('E53', 'Thiếu vitamin nhóm B khác'),
('E54', 'Thiếu acid ascorbic (vitamin C)'),
('E55', 'Thiếu vitamin D'),
('E56', 'Thiếu vitamin khác'),
('E58', 'Thiếu calci trong chế độ ăn'),
('E61', 'Thiếu nguyên tố dinh dưỡng khác'),
('E63', 'Thiếu dinh dưỡng khác'),
('E67', 'Thừa dinh dưỡng khác'),
('E79', 'Rối loạn chuyển hóa purin và pyrimidin (tăng acid uric máu)'),
('E83', 'Rối loạn chuyển hóa khoáng chất'),
('E86', 'Giảm thể tích tuần hoàn (mất nước)'),
('E87', 'Rối loạn khác về nước, điện giải và thăng bằng kiềm toan'),
('E88', 'Rối loạn chuyển hóa khác'),

-- ===== Chương V: Rối loạn tâm thần và hành vi (F00-F99) =====
('F03', 'Sa sút trí tuệ không xác định'),
('F05', 'Mê sảng không do rượu và chất tác động tâm thần'),
('F06', 'Rối loạn tâm thần khác do tổn thương và rối loạn chức năng não'),
('F10', 'Rối loạn tâm thần và hành vi do rượu'),
('F17', 'Rối loạn tâm thần và hành vi do thuốc lá'),
('F19', 'Rối loạn tâm thần và hành vi do sử dụng nhiều chất'),
('F20', 'Tâm thần phân liệt'),
('F22', 'Rối loạn hoang tưởng dai dẳng'),
('F23', 'Rối loạn loạn thần cấp và nhất thời'),
('F25', 'Rối loạn phân liệt cảm xúc'),
('F29', 'Loạn thần không thực tổn không xác định'),
('F31', 'Rối loạn cảm xúc lưỡng cực'),
('F33', 'Rối loạn trầm cảm tái diễn'),
('F34', 'Rối loạn khí sắc dai dẳng'),
('F40', 'Rối loạn lo âu ám ảnh sợ'),
('F42', 'Rối loạn ám ảnh nghi thức'),
('F43', 'Phản ứng với stress trầm trọng và rối loạn thích ứng'),
('F44', 'Rối loạn phân ly'),
('F45', 'Rối loạn dạng cơ thể'),
('F48', 'Rối loạn tâm căn khác (gồm suy nhược thần kinh)'),
('F50', 'Rối loạn ăn uống'),
('F51', 'Rối loạn giấc ngủ không thực tổn'),
('F52', 'Rối loạn chức năng tình dục không do bệnh thực thể'),
('F60', 'Rối loạn nhân cách đặc hiệu'),
('F70', 'Chậm phát triển tâm thần nhẹ'),
('F80', 'Rối loạn phát triển đặc hiệu về lời nói và ngôn ngữ'),
('F81', 'Rối loạn phát triển đặc hiệu về kỹ năng học tập'),
('F84', 'Rối loạn phát triển lan tỏa (gồm tự kỷ)'),
('F90', 'Rối loạn tăng động giảm chú ý'),
('F91', 'Rối loạn hành vi'),
('F95', 'Rối loạn tic'),
('F98', 'Rối loạn hành vi và cảm xúc khởi phát ở trẻ em'),

-- ===== Chương VI: Bệnh hệ thần kinh (G00-G99) =====
('G00', 'Viêm màng não do vi khuẩn'),
('G03', 'Viêm màng não do nguyên nhân khác và không xác định'),
('G06', 'Áp xe nội sọ và trong ống sống'),
('G20', 'Bệnh Parkinson'),
('G21', 'Hội chứng Parkinson thứ phát'),
('G24', 'Loạn trương lực cơ'),
('G25', 'Rối loạn vận động ngoại tháp khác'),
('G30', 'Bệnh Alzheimer'),
('G31', 'Bệnh thoái hóa khác của hệ thần kinh'),
('G35', 'Xơ cứng rải rác'),
('G40', 'Động kinh'),
('G41', 'Trạng thái động kinh'),
('G45', 'Cơn thiếu máu não thoáng qua'),
('G50', 'Rối loạn dây thần kinh sinh ba (đau dây V)'),
('G51', 'Rối loạn dây thần kinh mặt (gồm liệt Bell)'),
('G52', 'Rối loạn dây thần kinh sọ khác'),
('G54', 'Rối loạn rễ và đám rối thần kinh'),
('G56', 'Bệnh đơn dây thần kinh chi trên (gồm hội chứng ống cổ tay)'),
('G57', 'Bệnh đơn dây thần kinh chi dưới'),
('G58', 'Bệnh đơn dây thần kinh khác'),
('G60', 'Bệnh đa dây thần kinh di truyền và vô căn'),
('G62', 'Bệnh đa dây thần kinh khác'),
('G63', 'Bệnh đa dây thần kinh trong bệnh lý khác'),
('G70', 'Nhược cơ và rối loạn dẫn truyền thần kinh - cơ khác'),
('G80', 'Bại não'),
('G81', 'Liệt nửa người'),
('G82', 'Liệt hai chi dưới và liệt tứ chi'),
('G90', 'Rối loạn hệ thần kinh tự chủ'),
('G91', 'Não úng thủy'),
('G93', 'Rối loạn khác của não'),
('G95', 'Bệnh khác của tủy sống'),

-- ===== Chương VII: Bệnh mắt và phần phụ (H00-H59) =====
('H00', 'Chắp và lẹo'),
('H01', 'Viêm bờ mi và viêm khác của mi mắt'),
('H02', 'Rối loạn khác của mi mắt'),
('H04', 'Rối loạn bộ lệ'),
('H05', 'Rối loạn hốc mắt'),
('H11', 'Rối loạn khác của kết mạc (gồm mộng thịt)'),
('H16', 'Viêm giác mạc'),
('H17', 'Sẹo và đục giác mạc'),
('H18', 'Rối loạn khác của giác mạc'),
('H20', 'Viêm mống mắt thể mi'),
('H25', 'Đục thủy tinh thể tuổi già'),
('H26', 'Đục thủy tinh thể khác'),
('H33', 'Bong và rách võng mạc'),
('H35', 'Rối loạn khác của võng mạc'),
('H36', 'Rối loạn võng mạc trong bệnh lý khác (bệnh võng mạc đái tháo đường)'),
('H40', 'Glôcôm (tăng nhãn áp)'),
('H43', 'Rối loạn dịch kính'),
('H44', 'Rối loạn nhãn cầu'),
('H47', 'Rối loạn thần kinh thị và đường thị giác'),
('H49', 'Lác liệt'),
('H50', 'Lác khác'),
('H52', 'Tật khúc xạ và rối loạn điều tiết'),
('H53', 'Rối loạn thị giác'),
('H54', 'Mù và giảm thị lực'),
('H57', 'Rối loạn khác của mắt và phần phụ'),

-- ===== Chương VIII: Bệnh tai và xương chũm (H60-H95) =====
('H60', 'Viêm tai ngoài'),
('H61', 'Rối loạn khác của tai ngoài (gồm nút ráy tai)'),
('H65', 'Viêm tai giữa không mủ'),
('H68', 'Viêm và tắc vòi nhĩ'),
('H69', 'Rối loạn khác của vòi nhĩ'),
('H70', 'Viêm xương chũm và tình trạng liên quan'),
('H72', 'Thủng màng nhĩ'),
('H73', 'Rối loạn khác của màng nhĩ'),
('H83', 'Bệnh khác của tai trong'),
('H90', 'Nghe kém dẫn truyền và nghe kém tiếp nhận'),
('H91', 'Nghe kém khác'),
('H92', 'Đau tai và chảy dịch tai'),
('H93', 'Rối loạn khác của tai'),

-- ===== Chương IX: Bệnh hệ tuần hoàn (I00-I99) =====
('I05', 'Bệnh van hai lá do thấp'),
('I06', 'Bệnh van động mạch chủ do thấp'),
('I08', 'Bệnh nhiều van tim'),
('I12', 'Bệnh thận do tăng huyết áp'),
('I13', 'Bệnh tim và thận do tăng huyết áp'),
('I15', 'Tăng huyết áp thứ phát'),
('I21', 'Nhồi máu cơ tim cấp'),
('I24', 'Bệnh tim thiếu máu cục bộ cấp khác'),
('I26', 'Thuyên tắc phổi'),
('I27', 'Bệnh tim do phổi khác'),
('I30', 'Viêm màng ngoài tim cấp'),
('I34', 'Rối loạn van hai lá không do thấp'),
('I35', 'Rối loạn van động mạch chủ không do thấp'),
('I38', 'Viêm nội tâm mạc, van không xác định'),
('I42', 'Bệnh cơ tim'),
('I44', 'Blốc nhĩ thất và blốc nhánh trái'),
('I45', 'Rối loạn dẫn truyền khác'),
('I47', 'Nhịp nhanh kịch phát'),
('I49', 'Rối loạn nhịp tim khác'),
('I51', 'Biến chứng và bệnh tim mô tả không rõ'),
('I60', 'Xuất huyết dưới nhện'),
('I61', 'Xuất huyết trong não'),
('I62', 'Xuất huyết nội sọ khác không do chấn thương'),
('I64', 'Đột quỵ không xác định là xuất huyết hay nhồi máu'),
('I65', 'Tắc và hẹp động mạch trước não, không gây nhồi máu não'),
('I66', 'Tắc và hẹp động mạch não, không gây nhồi máu não'),
('I69', 'Di chứng bệnh mạch máu não'),
('I70', 'Xơ vữa động mạch'),
('I73', 'Bệnh mạch máu ngoại vi khác'),
('I74', 'Tắc và huyết khối động mạch'),
('I77', 'Rối loạn khác của động mạch và tiểu động mạch'),
('I80', 'Viêm tĩnh mạch và viêm tắc tĩnh mạch'),
('I82', 'Thuyên tắc và huyết khối tĩnh mạch khác'),
('I83', 'Giãn tĩnh mạch chi dưới'),
('I86', 'Giãn tĩnh mạch ở vị trí khác'),
('I87', 'Rối loạn khác của tĩnh mạch'),
('I88', 'Viêm hạch bạch huyết không đặc hiệu'),
('I89', 'Rối loạn không nhiễm khuẩn khác của mạch bạch huyết'),
('I95', 'Hạ huyết áp'),
('I99', 'Rối loạn khác của hệ tuần hoàn'),

-- ===== Chương X: Bệnh hệ hô hấp (J00-J99) =====
('J05', 'Viêm thanh quản và viêm nắp thanh môn cấp tắc nghẽn'),
('J10', 'Cúm do virus cúm đã định danh'),
('J12', 'Viêm phổi do virus'),
('J13', 'Viêm phổi do phế cầu'),
('J14', 'Viêm phổi do Haemophilus influenzae'),
('J15', 'Viêm phổi do vi khuẩn khác'),
('J16', 'Viêm phổi do tác nhân nhiễm khuẩn khác'),
('J17', 'Viêm phổi trong bệnh lý phân loại nơi khác'),
('J21', 'Viêm tiểu phế quản cấp'),
('J22', 'Nhiễm khuẩn hô hấp dưới cấp không xác định'),
('J31', 'Viêm mũi, viêm mũi họng và viêm họng mạn'),
('J33', 'Polyp mũi'),
('J34', 'Rối loạn khác của mũi và xoang (gồm vẹo vách ngăn)'),
('J35', 'Bệnh mạn tính của amidan và VA'),
('J36', 'Áp xe quanh amidan'),
('J37', 'Viêm thanh quản và viêm thanh khí quản mạn'),
('J38', 'Bệnh của dây thanh và thanh quản'),
('J39', 'Bệnh khác của đường hô hấp trên'),
('J41', 'Viêm phế quản mạn đơn thuần và nhầy mủ'),
('J42', 'Viêm phế quản mạn không xác định'),
('J43', 'Khí phế thũng'),
('J46', 'Trạng thái hen ác tính'),
('J47', 'Giãn phế quản'),
('J81', 'Phù phổi'),
('J84', 'Bệnh phổi kẽ khác'),
('J85', 'Áp xe phổi và trung thất'),
('J86', 'Mủ màng phổi'),
('J90', 'Tràn dịch màng phổi'),
('J93', 'Tràn khí màng phổi'),
('J94', 'Bệnh khác của màng phổi'),
('J96', 'Suy hô hấp'),
('J98', 'Rối loạn hô hấp khác'),

-- ===== Chương XI: Bệnh hệ tiêu hóa (K00-K93) =====
('K00', 'Rối loạn phát triển và mọc răng'),
('K02', 'Sâu răng'),
('K04', 'Bệnh của tủy răng và mô quanh chóp'),
('K05', 'Viêm lợi và bệnh quanh răng'),
('K08', 'Rối loạn khác của răng và cấu trúc nâng đỡ'),
('K11', 'Bệnh của tuyến nước bọt'),
('K12', 'Viêm miệng và tổn thương liên quan (nhiệt miệng)'),
('K13', 'Bệnh khác của môi và niêm mạc miệng'),
('K14', 'Bệnh của lưỡi'),
('K20', 'Viêm thực quản'),
('K22', 'Bệnh khác của thực quản'),
('K27', 'Loét dạ dày - tá tràng không xác định vị trí'),
('K28', 'Loét dạ dày - hỗng tràng'),
('K31', 'Bệnh khác của dạ dày và tá tràng'),
('K35', 'Viêm ruột thừa cấp'),
('K36', 'Viêm ruột thừa khác'),
('K37', 'Viêm ruột thừa không xác định'),
('K40', 'Thoát vị bẹn'),
('K41', 'Thoát vị đùi'),
('K42', 'Thoát vị rốn'),
('K43', 'Thoát vị thành bụng'),
('K44', 'Thoát vị hoành'),
('K46', 'Thoát vị ổ bụng không xác định'),
('K50', 'Bệnh Crohn'),
('K51', 'Viêm loét đại tràng'),
('K55', 'Rối loạn mạch máu của ruột'),
('K56', 'Tắc ruột cơ học và liệt ruột'),
('K57', 'Bệnh túi thừa ruột'),
('K60', 'Nứt và rò vùng hậu môn trực tràng'),
('K61', 'Áp xe vùng hậu môn trực tràng'),
('K62', 'Bệnh khác của hậu môn và trực tràng'),
('K63', 'Bệnh khác của ruột'),
('K65', 'Viêm phúc mạc'),
('K70', 'Bệnh gan do rượu'),
('K71', 'Bệnh gan nhiễm độc'),
('K72', 'Suy gan'),
('K73', 'Viêm gan mạn, không phân loại nơi khác'),
('K74', 'Xơ hóa và xơ gan'),
('K75', 'Bệnh viêm gan khác'),
('K80', 'Sỏi mật'),
('K81', 'Viêm túi mật'),
('K82', 'Bệnh khác của túi mật'),
('K83', 'Bệnh khác của đường mật'),
('K85', 'Viêm tụy cấp'),
('K86', 'Bệnh khác của tụy'),
('K90', 'Kém hấp thu ở ruột'),
('K92', 'Bệnh khác của hệ tiêu hóa (gồm nôn ra máu, đi ngoài phân đen)'),

-- ===== Chương XII: Bệnh da và mô dưới da (L00-L99) =====
('L01', 'Chốc'),
('L03', 'Viêm mô tế bào'),
('L04', 'Viêm hạch bạch huyết cấp'),
('L05', 'U nang lông'),
('L08', 'Nhiễm khuẩn tại chỗ khác của da và mô dưới da'),
('L21', 'Viêm da tiết bã'),
('L22', 'Viêm da tã lót'),
('L24', 'Viêm da tiếp xúc kích ứng'),
('L25', 'Viêm da tiếp xúc không xác định'),
('L27', 'Viêm da do chất dùng đường toàn thân (dị ứng thuốc)'),
('L28', 'Lichen đơn mạn và sẩn ngứa'),
('L29', 'Ngứa'),
('L40', 'Vảy nến'),
('L42', 'Vảy phấn hồng'),
('L43', 'Lichen phẳng'),
('L51', 'Hồng ban đa dạng'),
('L53', 'Tình trạng hồng ban khác'),
('L55', 'Bỏng nắng'),
('L60', 'Bệnh của móng'),
('L63', 'Rụng tóc từng vùng'),
('L64', 'Rụng tóc kiểu androgen'),
('L65', 'Rụng tóc không sẹo khác'),
('L66', 'Rụng tóc có sẹo'),
('L70', 'Trứng cá'),
('L71', 'Trứng cá đỏ'),
('L72', 'U nang nang lông của da và mô dưới da'),
('L73', 'Rối loạn khác của nang lông'),
('L74', 'Rối loạn tuyến mồ hôi ngoại tiết'),
('L80', 'Bạch biến'),
('L81', 'Rối loạn sắc tố khác (nám da)'),
('L82', 'Dày sừng tiết bã'),
('L84', 'Chai chân và vết chai'),
('L85', 'Dày sừng biểu bì khác'),
('L89', 'Loét do tì đè'),
('L90', 'Tổn thương da teo'),
('L91', 'Tổn thương da phì đại (sẹo lồi)'),
('L92', 'Tổn thương dạng u hạt của da và mô dưới da'),
('L93', 'Lupus ban đỏ'),
('L94', 'Tổn thương mô liên kết khu trú khác'),
('L97', 'Loét chi dưới, không phân loại nơi khác'),
('L98', 'Rối loạn khác của da và mô dưới da'),

-- ===== Chương XIII: Bệnh hệ cơ - xương - khớp và mô liên kết (M00-M99) =====
('M00', 'Viêm khớp nhiễm khuẩn (viêm khớp mủ)'),
('M05', 'Viêm khớp dạng thấp huyết thanh dương tính'),
('M06', 'Viêm khớp dạng thấp khác'),
('M08', 'Viêm khớp thiếu niên'),
('M11', 'Bệnh khớp do tinh thể khác'),
('M19', 'Thoái hóa khớp khác'),
('M20', 'Biến dạng mắc phải của ngón tay và ngón chân'),
('M21', 'Biến dạng mắc phải khác của chi'),
('M22', 'Rối loạn của xương bánh chè'),
('M23', 'Tổn thương khớp gối trong'),
('M24', 'Tổn thương khớp đặc hiệu khác'),
('M32', 'Lupus ban đỏ hệ thống'),
('M33', 'Viêm da cơ'),
('M34', 'Xơ cứng bì hệ thống'),
('M35', 'Bệnh hệ thống khác của mô liên kết (gồm hội chứng Sjögren)'),
('M40', 'Gù và ưỡn cột sống'),
('M41', 'Vẹo cột sống'),
('M42', 'Thoái hóa cột sống ở tuổi thiếu niên và người lớn'),
('M43', 'Bệnh biến dạng khác của cột sống (trượt đốt sống)'),
('M45', 'Viêm cột sống dính khớp'),
('M46', 'Bệnh viêm cột sống khác'),
('M48', 'Bệnh cột sống khác (gồm hẹp ống sống)'),
('M50', 'Bệnh đĩa đệm cột sống cổ'),
('M51', 'Bệnh đĩa đệm khác (thoát vị đĩa đệm thắt lưng)'),
('M53', 'Bệnh lưng khác, không phân loại nơi khác'),
('M54.2', 'Đau cổ'),
('M54.3', 'Đau thần kinh tọa'),
('M54.4', 'Đau thắt lưng kèm đau thần kinh tọa'),
('M60', 'Viêm cơ'),
('M65', 'Viêm màng hoạt dịch và viêm bao gân'),
('M66', 'Đứt tự phát màng hoạt dịch và gân'),
('M67', 'Rối loạn khác của màng hoạt dịch và gân'),
('M70', 'Rối loạn mô mềm do sử dụng quá mức và do tì đè'),
('M71', 'Bệnh túi thanh dịch khác'),
('M72', 'Rối loạn nguyên bào sợi'),
('M75', 'Tổn thương vai (viêm quanh khớp vai)'),
('M76', 'Bệnh gân chi dưới, trừ bàn chân'),
('M77', 'Bệnh gân khác (gồm viêm lồi cầu xương cánh tay)'),
('M80', 'Loãng xương có gãy xương bệnh lý'),
('M81', 'Loãng xương không có gãy xương bệnh lý'),
('M84', 'Rối loạn liền xương'),
('M86', 'Viêm tủy xương'),
('M87', 'Hoại tử xương'),
('M89', 'Bệnh khác của xương'),
('M94', 'Rối loạn khác của sụn'),

-- ===== Chương XIV: Bệnh hệ tiết niệu - sinh dục (N00-N99) =====
('N00', 'Hội chứng viêm cầu thận cấp'),
('N02', 'Đái máu tái diễn và dai dẳng'),
('N03', 'Hội chứng viêm cầu thận mạn'),
('N04', 'Hội chứng thận hư'),
('N05', 'Hội chứng viêm cầu thận không xác định'),
('N10', 'Viêm thận kẽ ống thận cấp (viêm thận - bể thận cấp)'),
('N11', 'Viêm thận kẽ ống thận mạn'),
('N12', 'Viêm thận kẽ ống thận không xác định cấp hay mạn'),
('N13', 'Bệnh thận do tắc nghẽn và trào ngược'),
('N17', 'Suy thận cấp'),
('N19', 'Suy thận không xác định'),
('N21', 'Sỏi đường tiết niệu dưới'),
('N23', 'Cơn đau quặn thận không xác định'),
('N28', 'Rối loạn khác của thận và niệu quản (gồm nang thận)'),
('N31', 'Rối loạn thần kinh - cơ của bàng quang'),
('N32', 'Rối loạn khác của bàng quang'),
('N34', 'Viêm niệu đạo và hội chứng niệu đạo'),
('N35', 'Hẹp niệu đạo'),
('N41', 'Bệnh viêm của tuyến tiền liệt'),
('N43', 'Tràn dịch màng tinh hoàn và nang thừng tinh'),
('N44', 'Xoắn tinh hoàn'),
('N45', 'Viêm tinh hoàn và viêm mào tinh hoàn'),
('N46', 'Vô sinh nam'),
('N47', 'Hẹp bao quy đầu và dài bao quy đầu'),
('N48', 'Rối loạn khác của dương vật'),
('N50', 'Rối loạn khác của cơ quan sinh dục nam'),
('N60', 'Loạn sản lành tính của tuyến vú'),
('N61', 'Bệnh viêm của vú (viêm tuyến vú)'),
('N63', 'Khối u ở vú không xác định'),
('N64', 'Rối loạn khác của vú'),
('N70', 'Viêm vòi trứng và viêm buồng trứng'),
('N71', 'Bệnh viêm của tử cung, trừ cổ tử cung'),
('N72', 'Bệnh viêm của cổ tử cung'),
('N73', 'Bệnh viêm vùng chậu nữ khác'),
('N75', 'Bệnh của tuyến Bartholin'),
('N80', 'Lạc nội mạc tử cung'),
('N81', 'Sa sinh dục nữ'),
('N83', 'Rối loạn không viêm của buồng trứng, vòi trứng và dây chằng rộng'),
('N84', 'Polyp đường sinh dục nữ'),
('N85', 'Rối loạn không viêm khác của tử cung'),
('N86', 'Trợt và lộ tuyến cổ tử cung'),
('N87', 'Loạn sản cổ tử cung'),
('N88', 'Rối loạn không viêm khác của cổ tử cung'),
('N89', 'Rối loạn không viêm khác của âm đạo'),
('N91', 'Kinh thưa, vô kinh và ít kinh'),
('N92', 'Kinh nhiều, kinh thường xuyên và kinh không đều'),
('N93', 'Chảy máu bất thường khác của tử cung và âm đạo'),
('N94', 'Đau và tình trạng khác liên quan cơ quan sinh dục nữ và chu kỳ kinh nguyệt'),
('N97', 'Vô sinh nữ'),

-- ===== Chương XV: Thai nghén, sinh đẻ và hậu sản (O00-O99) =====
('O21', 'Nôn quá mức trong thai kỳ'),
('O23', 'Nhiễm khuẩn đường tiết niệu - sinh dục trong thai kỳ'),
('O24', 'Đái tháo đường trong thai kỳ'),
('O26', 'Chăm sóc bà mẹ vì tình trạng khác liên quan thai nghén'),
('O99', 'Bệnh khác của mẹ gây biến chứng thai nghén, sinh đẻ và hậu sản'),

-- ===== Chương XVI: Bệnh lý thời kỳ chu sinh (P00-P96) =====
('P59', 'Vàng da sơ sinh do nguyên nhân khác và không xác định'),
('P92', 'Vấn đề nuôi dưỡng ở trẻ sơ sinh'),

-- ===== Chương XVII: Dị tật bẩm sinh (Q00-Q99) =====
('Q21', 'Dị tật bẩm sinh của vách tim'),
('Q53', 'Tinh hoàn ẩn'),
('Q54', 'Lỗ đái lệch thấp'),
('Q65', 'Dị tật bẩm sinh của khớp háng'),
('Q66', 'Dị tật bẩm sinh của bàn chân'),
('Q82', 'Dị tật bẩm sinh khác của da'),

-- ===== Chương XVIII: Triệu chứng và dấu hiệu (R00-R99) =====
('R00', 'Bất thường nhịp tim (đánh trống ngực)'),
('R01', 'Tiếng thổi tim và âm thanh tim khác'),
('R03', 'Trị số huyết áp bất thường, chưa có chẩn đoán'),
('R04', 'Chảy máu từ đường hô hấp (gồm chảy máu cam)'),
('R06', 'Bất thường về hô hấp (khó thở)'),
('R07', 'Đau họng và đau ngực'),
('R09', 'Triệu chứng khác của hệ tuần hoàn và hô hấp'),
('R12', 'Ợ nóng'),
('R13', 'Khó nuốt'),
('R14', 'Đầy hơi và tình trạng liên quan'),
('R15', 'Đại tiện không tự chủ'),
('R16', 'Gan to và lách to, không phân loại nơi khác'),
('R17', 'Vàng da không xác định'),
('R18', 'Cổ trướng'),
('R19', 'Triệu chứng khác của hệ tiêu hóa và ổ bụng'),
('R20', 'Rối loạn cảm giác da'),
('R21', 'Ban và phát ban da khác'),
('R22', 'Sưng, u cục khu trú ở da và mô dưới da'),
('R23', 'Thay đổi khác của da'),
('R25', 'Cử động bất thường không tự chủ'),
('R26', 'Bất thường dáng đi và vận động'),
('R27', 'Thiếu phối hợp vận động khác'),
('R29', 'Triệu chứng khác của hệ thần kinh và cơ xương'),
('R30', 'Đau khi đi tiểu'),
('R31', 'Đái máu không xác định'),
('R32', 'Đái không tự chủ không xác định'),
('R33', 'Bí tiểu'),
('R35', 'Đái nhiều'),
('R36', 'Chảy dịch niệu đạo'),
('R39', 'Triệu chứng khác của hệ tiết niệu'),
('R40', 'Ngủ gà, sững sờ và hôn mê'),
('R41', 'Triệu chứng khác về nhận thức và ý thức'),
('R43', 'Rối loạn khứu giác và vị giác'),
('R44', 'Triệu chứng khác về cảm giác và tri giác'),
('R45', 'Triệu chứng liên quan trạng thái cảm xúc'),
('R46', 'Triệu chứng liên quan hình dáng và hành vi'),
('R47', 'Rối loạn lời nói, không phân loại nơi khác'),
('R49', 'Rối loạn giọng nói'),
('R52', 'Đau, không phân loại nơi khác'),
('R55', 'Ngất và xỉu'),
('R56', 'Co giật, không phân loại nơi khác'),
('R57', 'Sốc, không phân loại nơi khác'),
('R58', 'Xuất huyết, không phân loại nơi khác'),
('R59', 'Hạch to'),
('R60', 'Phù, không phân loại nơi khác'),
('R61', 'Ra mồ hôi nhiều'),
('R63', 'Triệu chứng liên quan ăn uống (chán ăn, sụt cân)'),
('R68', 'Triệu chứng và dấu hiệu chung khác'),
('R69', 'Nguyên nhân bệnh chưa rõ'),
('R73', 'Tăng glucose máu (rối loạn dung nạp glucose)'),
('R74', 'Tăng men huyết thanh bất thường'),
('R79', 'Bất thường khác trong hóa sinh máu'),
('R80', 'Protein niệu đơn thuần'),
('R82', 'Bất thường khác trong nước tiểu'),
('R87', 'Bất thường bệnh phẩm từ cơ quan sinh dục nữ'),
('R94', 'Kết quả thăm dò chức năng bất thường'),

-- ===== Chương XIX: Chấn thương, ngộ độc (S00-T98) =====
('S00', 'Chấn thương nông ở đầu'),
('S01', 'Vết thương hở ở đầu'),
('S02', 'Gãy xương sọ và xương mặt'),
('S06', 'Chấn thương nội sọ (gồm chấn động não)'),
('S09', 'Chấn thương khác và không xác định ở đầu'),
('S13', 'Trật khớp, bong gân và căng dây chằng khớp, dây chằng vùng cổ'),
('S16', 'Chấn thương cơ và gân vùng cổ'),
('S20', 'Chấn thương nông ở ngực'),
('S22', 'Gãy xương sườn, xương ức và cột sống ngực'),
('S30', 'Chấn thương nông ở bụng, thắt lưng và chậu hông'),
('S32', 'Gãy cột sống thắt lưng và khung chậu'),
('S39', 'Chấn thương khác của bụng, thắt lưng và chậu hông'),
('S40', 'Chấn thương nông ở vai và cánh tay'),
('S41', 'Vết thương hở ở vai và cánh tay'),
('S42', 'Gãy xương vùng vai và cánh tay'),
('S43', 'Trật khớp, bong gân và căng dây chằng vùng vai'),
('S50', 'Chấn thương nông ở cẳng tay'),
('S51', 'Vết thương hở ở cẳng tay'),
('S52', 'Gãy xương cẳng tay'),
('S53', 'Trật khớp, bong gân và căng dây chằng khuỷu tay'),
('S60', 'Chấn thương nông ở cổ tay và bàn tay'),
('S61', 'Vết thương hở ở cổ tay và bàn tay'),
('S62', 'Gãy xương ở cổ tay và bàn tay'),
('S63', 'Trật khớp, bong gân và căng dây chằng cổ tay, bàn tay'),
('S66', 'Chấn thương cơ và gân vùng cổ tay, bàn tay'),
('S70', 'Chấn thương nông ở háng và đùi'),
('S72', 'Gãy xương đùi'),
('S76', 'Chấn thương cơ và gân vùng háng, đùi'),
('S80', 'Chấn thương nông ở cẳng chân'),
('S81', 'Vết thương hở ở cẳng chân'),
('S82', 'Gãy xương cẳng chân, gồm cổ chân'),
('S83', 'Trật khớp, bong gân và căng dây chằng khớp gối'),
('S86', 'Chấn thương cơ và gân vùng cẳng chân'),
('S90', 'Chấn thương nông ở cổ chân và bàn chân'),
('S91', 'Vết thương hở ở cổ chân và bàn chân'),
('S92', 'Gãy xương bàn chân, trừ cổ chân'),
('S93', 'Trật khớp, bong gân và căng dây chằng cổ chân, bàn chân'),
('T14', 'Chấn thương vùng cơ thể không xác định'),
('T15', 'Dị vật ở mắt ngoài'),
('T16', 'Dị vật trong tai'),
('T17', 'Dị vật đường hô hấp'),
('T18', 'Dị vật đường tiêu hóa'),
('T20', 'Bỏng vùng đầu và cổ'),
('T21', 'Bỏng thân mình'),
('T22', 'Bỏng vai và chi trên, trừ cổ tay và bàn tay'),
('T23', 'Bỏng cổ tay và bàn tay'),
('T24', 'Bỏng háng và chi dưới, trừ cổ chân và bàn chân'),
('T25', 'Bỏng cổ chân và bàn chân'),
('T30', 'Bỏng không xác định vị trí'),
('T36', 'Ngộ độc thuốc kháng sinh dùng đường toàn thân'),
('T39', 'Ngộ độc thuốc giảm đau, hạ sốt không phải opioid'),
('T50', 'Ngộ độc thuốc và chất khác'),
('T63', 'Tác dụng độc do tiếp xúc động vật có nọc (rắn cắn, ong đốt)'),
('T65', 'Tác dụng độc của chất khác và không xác định'),
('T88', 'Biến chứng khác của chăm sóc phẫu thuật và y tế'),

-- ===== Chương XXI: Yếu tố ảnh hưởng sức khỏe và tiếp xúc dịch vụ y tế (Z00-Z99) =====
('Z01', 'Khám và thăm dò đặc biệt khác'),
('Z02', 'Khám vì mục đích hành chính'),
('Z03', 'Theo dõi y tế vì nghi ngờ bệnh'),
('Z09', 'Khám theo dõi sau điều trị'),
('Z11', 'Sàng lọc bệnh nhiễm khuẩn và ký sinh trùng'),
('Z12', 'Sàng lọc u tân sinh'),
('Z13', 'Sàng lọc rối loạn khác'),
('Z20', 'Tiếp xúc và phơi nhiễm bệnh truyền nhiễm'),
('Z23', 'Tiêm chủng phòng một bệnh do vi khuẩn'),
('Z24', 'Tiêm chủng phòng một bệnh do virus'),
('Z25', 'Tiêm chủng phòng bệnh do virus khác'),
('Z27', 'Tiêm chủng phối hợp nhiều bệnh'),
('Z30', 'Quản lý tránh thai'),
('Z32', 'Khám và xét nghiệm xác định thai nghén'),
('Z34', 'Theo dõi thai nghén bình thường'),
('Z35', 'Theo dõi thai nghén nguy cơ cao'),
('Z39', 'Chăm sóc và khám sau sinh'),
('Z51', 'Chăm sóc y tế đặc hiệu khác'),
('Z71', 'Người tìm tư vấn sức khỏe'),
('Z76', 'Người tiếp xúc dịch vụ y tế trong hoàn cảnh khác'),
('Z79', 'Đang dùng thuốc dài ngày'),
('Z86', 'Tiền sử bản thân có bệnh khác'),
('Z87', 'Tiền sử bản thân có bệnh và tình trạng khác'),
('Z88', 'Tiền sử dị ứng thuốc'),
('Z91', 'Tiền sử có yếu tố nguy cơ khác')

-- 86 mã seed từ V4 đã có sẵn: bỏ qua thay vì ghi đè, để migration chạy lại được an toàn.
on conflict (code) do nothing;
